apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: my-app.local
      http:
        paths:
         
          - path: "/devopsdemo(/|$)(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "dev-ops-demo-helm-chart.fullname" . }}
                port:
                  number: 8080 #Change this to 8085 if container listens there